server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: SmartsTestProject

  datasource:
    url: jdbc:hsqldb:file:TestHSQLDB; hsqldb.lock_file=false
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql

  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none